// One runner for every suite → prints a summary AND writes docs/RECEIPTS.md
// with each suite's full observed output. This file IS the receipt: every
// function, exercised, with the command that ran it and what came back.
import { spawnSync } from 'node:child_process';
import { writeFileSync, readFileSync } from 'node:fs';

const SUITES = [
  ['Unit', 'test/unit.mjs', 'Pure functions in isolation: safe-arith evaluator, checker engine, Persona+ compilers, schema builders, scheduler math, token compare.'],
  ['Function', 'test/function.mjs', 'Every HTTP endpoint contract + shape, plus data-store durability (corrupt/truncated JSON fails soft).'],
  ['Connection', 'test/connection.mjs', 'Live WebSocket + PTY: authed connect, 4001 on bad token, malformed-frame survival, multi-client broadcast, tmux round-trip, reconnection.'],
  ['Security/Penetration', 'test/security.mjs', 'Auth bypass, SSRF (preview + harness), secret exfiltration, path traversal, stored-XSS, oversized-body DoS, profile privilege-escalation.'],
  ['Adversarial', 'test/adversarial.mjs', 'Malformed/oversized/hostile input across all surfaces; profile tool-blocking; preflight honesty.'],
  ['E2E', 'test/e2e.mjs', 'Real flows: fleet run to completion, budget-halt→top-up resume, harness good/bad + escalation, routine fire→inbox.'],
  ['UI/UX', 'test/ui.spec.mjs', 'Headless Chromium drives the real cockpit: tabs, engine roster, doctor/preflight render, key entry no-leak, XSS-safe render.'],
  ['Tour/Onboarding', 'test/tour.spec.mjs', 'Drives all tour steps live — every step spotlights a real visible element; handbook opens/searches/relaunches.'],
];

const now = process.env.RECEIPT_STAMP || 'see git log';
let md = `# ATLAN — Test Receipts\n\n`;
md += `Generated by \`node test/run-all.mjs\`. Every suite below ran against the live server at 127.0.0.1:4589.\n`;
md += `This document is the evidence trail: each function is exercised, and the raw pass/fail output is captured verbatim so it can be checked independently.\n\n`;
md += `_Stamp: ${now}_\n\n## Summary\n\n| Suite | What it proves | Result |\n|---|---|---|\n`;

const details = [];
let allPass = 0, allFail = 0, hardFail = false;
for (const [name, file, desc] of SUITES) {
  process.stderr.write(`running ${name}…\n`);
  const res = spawnSync('node', [file], { encoding: 'utf8', timeout: 600000, cwd: new URL('..', import.meta.url).pathname });
  const out = (res.stdout || '') + (res.stderr || '');
  const m = out.match(/(\d+) passed, (\d+) failed/);
  const p = m ? +m[1] : 0, f = m ? +m[2] : (res.status === 0 ? 0 : 1);
  allPass += p; allFail += f;
  if (res.status !== 0) hardFail = true;
  const verdict = f === 0 && res.status === 0 ? `✅ ${p}/${p}` : `❌ ${p} pass, ${f} fail`;
  md += `| ${name} | ${desc} | ${verdict} |\n`;
  details.push(`## ${name}\n\n${desc}\n\n\`\`\`\n$ node ${file}\n${out.trim()}\n\`\`\`\n`);
}

md += `\n**Total: ${allPass} passed, ${allFail} failed across ${SUITES.length} suites.**\n\n`;
md += details.join('\n');
writeFileSync(new URL('../docs/RECEIPTS.md', import.meta.url), md);
console.log(`\n═══ ${allPass} passed, ${allFail} failed across ${SUITES.length} suites ═══`);
console.log('receipts → docs/RECEIPTS.md');
process.exit(hardFail || allFail ? 1 : 0);
